language: cpp
comiler:
 - gcc
 - clang

before_install:
 - sudo apt-get update -qq
 - wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz
 - wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/parmetis-4.0.3.tar.gz

install:
 - sudo apt-get install -qq openmpi-bin openmpi-common openmpi-dev libhdf5-openmpi-1.8.4 hdf5-tools libhdf5-openmpi-dev
 - tar -xaf metis-5.1.0.tar.gz
 - cd metis-5.1.0 && make config prefix=/usr && make && make install && cd ..
 - cd parmetis-4.0.3 && make config prefix=/usr && make && make install && cd ..

before_script:
 - export CC=mpicc
 - export CXX=mpicxx

script:
 - cd test/
 - git clone https://github.com/TUM-I5/XdmfWriter.git
 - scons

after_script:
 - cat config.log
