dist: bionic
language: cpp
comiler:
 - gcc
 - clang

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq

install:
 - |
  sudo apt-get update
  sudo apt-get install gcc-8 g++-8 gfortran-8 cmake
  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
  sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100
  sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-8 100
  sudo apt-get install -qq openmpi-bin openmpi-common libopenmpi-dev hdf5-tools libhdf5-openmpi-100 libhdf5-openmpi-dev libmetis-dev libparmetis-dev

before_script:
 - export CTEST_OUTPUT_ON_FAILURE=1
 - export OMPI_MCA_rmaps_base_oversubscribe=1
 - export OMPI_MCA_btl=vader,self

script:
 - cd test/
 - git clone https://github.com/TUM-I5/XdmfWriter.git
 - cd XdmfWriter && git checkout dev && cd ..
 - mkdir build && cd build && cmake .. && make
 - mpirun -n 2 ./tests ../test_data/mesh.h5 out
