#!/usr/bin/env python

# @file
#  This file is part of PUML
#
#  For conditions of distribution and use, please see the copyright
#  notice in the file 'COPYING' at the root directory of this package
#  and the copyright notice at https://github.com/TUM-I5/PUMGen
#
# @copyright 2017 Technische Universitaet Muenchen
# @author Sebastian Rettenberger <rettenbs@in.tum.de>
#

import os
import libs
import utils.variables

vars = utils.variables.Variables()

# Add build type
vars.AddBuildType()

# Add prefix path variable
vars.AddPrefixPathVariable()

# Add compiler variables
vars.AddCompilerVariable()

env = Environment(variables=vars)
env['ENV'] = os.environ

# Generate help
vars.SetHelpText(env)

# Check for any unknown (maybe misspelled) variables
vars.CheckUnknownVariables(env)

# Set prefix pathes from user
vars.SetPrefixPathes(env)

# Set compiler
env['CC'] = 'mpicc'
env['CXX'] = 'mpicxx'
vars.SetCompiler(env)

# Compiler flags
env.Append(CXXFLAGS=['-std=c++11'])
if env['buildType'] in ['release', 'relWithDebInfo']:
	env.Append(CXXFLAGS=['-O3'])
if env['buildType'] in ['debug', 'relWithDebInfo']:
	env.Append(CXXFLAGS=['-g'])

# Defines
env.Append(CPPDEFINES=['USE_MPI'])

# Add METIS
libs.find(env, 'metis', parallel=True)

# Add HDF5
libs.find(env, 'hdf5', parallel=True)

# Include directories
env.Append(CPPPATH=['#/..', '#/../submodules'])

buildDir = 'build'

env.Program('#/build/pumltest', ['puml.cpp'])